server:
  port: 8760
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: pgdemo-commons

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
    url: @db.url@
    username: @db.user@
    password: @db.password@

mybatis:
  type-aliases-package: com.rockbb.pgdemo.commons.api.dto
  mapper-locations: classpath:mapper/*.xml
